services:
  ocr-api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    restart: unless-stopped
    # Limit resources
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    # Add volume for temporary files if needed
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
